# Generated by Django 5.2.7 on 2025-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
