# Generated by Django 5.2.7 on 2025-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'No Preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('non_vegetarian', 'Non-Vegetarian'), ('dairy_free', 'Dairy Free'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein')], default='none', max_length=50),
        ),
    ]
