# Generated by Django 5.2.7 on 2025-11-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentuser_dietary_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Active')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='meal_frequency',
            field=models.CharField(choices=[('3_meals', '3 Meals a Day'), ('5_meals', '5 Small Meals a Day')], default='3_meals', max_length=20),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='weekly_budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='is_verified_university_email',
            field=models.BooleanField(default=False),
        ),
    ]
