# Generated by Django 5.2.7 on 2025-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentuser_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='goal',
            field=models.CharField(blank=True, choices=[('general_health', 'General Health'), ('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintain_weight', 'Maintain Weight')], max_length=50),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='max_calories',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum calories per meal', null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='notes',
            field=models.TextField(blank=True, help_text='Allergies or special notes'),
        ),
    ]
