# Generated by Django 5.2.7 on 2025-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentuser_goal_studentuser_max_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='daily_calorie_goal',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='dietary_preference',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='max_calories',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='meal_frequency',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='weekly_budget_limit',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(help_text='University email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='student_id',
            field=models.CharField(help_text='Unique university student ID', max_length=50, unique=True),
        ),
    ]
