# Generated by Django 5.2.7 on 2025-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftovers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftover',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leftover',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leftover',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
