# Generated by Django 5.2.7 on 2025-11-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leftovers', '0002_leftover_expiry_date_leftover_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftover',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='leftover',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='leftover',
            name='quantity',
        ),
    ]
