# Generated by Django 5.2.7 on 2025-11-13 05:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_mealquiz_food_preference'),
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nutritionlog',
            unique_together={('user', 'meal', 'date')},
        ),
    ]
