# Generated by Django 5.2.7 on 2025-11-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_nutritionlog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nutritionlog',
            unique_together=set(),
        ),
    ]
