# Generated by Django 5.2.7 on 2025-11-13 05:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_mealquiz_food_preference'),
        ('nutrition', '0003_alter_nutritionlog_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionlog',
            unique_together={('user', 'meal', 'date')},
        ),
    ]
