# Generated by Django 5.2.7 on 2025-11-05 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['meal_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['-week_start_date']},
        ),
        migrations.AlterModelOptions(
            name='mealplanitem',
            options={'ordering': ['day_of_week', 'meal_time']},
        ),
        migrations.AddField(
            model_name='meal',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='fiber',
            field=models.FloatField(blank=True, help_text='grams', null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='price_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approx. cost per serving in ₹', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='sodium',
            field=models.FloatField(blank=True, help_text='mg', null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='sugar',
            field=models.FloatField(blank=True, help_text='grams', null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(blank=True, help_text='e.g., Weight Loss, Muscle Gain', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(default='My Weekly Plan', max_length=255),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='total_calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Custom notes or modifications for this meal'),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='portion_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of servings'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(blank=True, help_text='grams', null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(blank=True, help_text='grams', null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(help_text='List ingredients separated by commas'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(blank=True, help_text='grams', null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='week_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
