# Generated by Django 5.2.7 on 2025-11-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_alter_meal_options_alter_mealplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dietary_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.AlterField(
            model_name='meal',
            name='price_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approx. cost per serving in $', max_digits=6, null=True),
        ),
    ]
