# Generated by Django 5.2.7 on 2025-11-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_meal_options_remove_meal_dietary_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='sugar',
        ),
        migrations.AddField(
            model_name='meal',
            name='area',
            field=models.CharField(blank=True, help_text='Country or region of origin', max_length=100),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Beef, Chicken, Vegan', max_length=100),
        ),
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags from API', max_length=255),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=300, help_text='Estimated calories per serving'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cooking_time',
            field=models.PositiveIntegerField(default=30, help_text='Approximate cooking time in minutes'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients, comma-separated'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Custom notes or modifications'),
        ),
    ]
