# Generated by Django 5.2.7 on 2025-11-06 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_remove_meal_fiber_remove_meal_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget per week in USD', max_digits=8, null=True)),
                ('meal_frequency', models.CharField(choices=[('3_meals', '3 Meals a Day'), ('5_meals', '5 Small Meals a Day')], default='3_meals', max_length=20)),
                ('goal', models.CharField(choices=[('general_health', 'General Health'), ('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintain_weight', 'Maintain Weight')], default='general_health', max_length=50)),
                ('max_calories', models.PositiveIntegerField(blank=True, help_text='Max calories per meal', null=True)),
                ('notes', models.TextField(blank=True, help_text='Allergies or special notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
