# Generated by Django 5.2.7 on 2025-11-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_mealquiz'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplanitem',
            unique_together=set(),
        ),
    ]
