# Generated by Django 5.2.7 on 2025-11-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_alter_mealplanitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealquiz',
            name='food_preference',
            field=models.CharField(choices=[('omnivore', 'Omnivore (All Foods)'), ('meat_lover', 'Meat Lover'), ('pescatarian', 'Pescatarian'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('high_protein', 'High Protein / Gym Diet'), ('light_meals', 'Breakfast & Light Meals'), ('sweet_tooth', 'Sweet Tooth / Dessert Lover')], default='omnivore', help_text='Preferred type of meals (e.g., Vegetarian, Vegan, etc.)', max_length=30),
        ),
    ]
